In [1]:
import os
import re
import json
from datetime import datetime
import random
from collections import defaultdict
import pandas as pd
from dotenv import load_dotenv
from langchain_groq import ChatGroq
load_dotenv()

/Volumes/LaCie/Projects_portfolio/IntelliQA/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

True

In [3]:
# Import all necessary libraries
from src.eval import (prepare_testset_documents, 
                    generate_rag_responses, 
                    run_batch_evaluation, 
                    get_score, 
                    save_file, 
                    get_results,
                    unanswerable_responses,
                    display_context_recall_failures
                    )
from rag_pipeline.query_engine import vectorstore

# 1. Test Dataset Generation from Documents

In [193]:
docs = prepare_testset_documents("evaluation/eval_data", chunk_size=1000, chunk_overlap=150)

In [195]:
docs[0]

Document(metadata={'session_id': 'test_session', 'filename': 'MSFT-anual-report.html'}, page_content='10-K')

In [5]:
df = pd.read_json("evaluation/testset/new_testset.jsonl", lines=True)

In [14]:
df['user_input'][100]

'What role does the Fos Proto-Oncogene play in the central nervous system according to the provided context, and how is it related to other key genes identified in the network analysis?'

In [15]:
REWRITE_PROMPT = """You are refining evaluation questions so each one is self-contained and unambiguous about its source.

You are given a QUESTION and the SOURCE it was generated from.

Rules:
1. If the question is already specific and clearly answerable on its own (it names the entity, gene, product, or topic it is about), return it UNCHANGED.
2. If the question uses vague references like "the company", "our", "the provided context", "this study" and does NOT name the specific source entity, rewrite it minimally to name the entity from the source. Change nothing else.
3. Do not add facts. Do not change the meaning. Only add the source identity when it is missing.

SOURCE: {source}
QUESTION: {question}

Return ONLY the final question text, nothing else."""

In [34]:
def clean_source(filename):
    name = filename.split('.',1)[0]
    return name.replace('-',' ').replace("_"," ").strip()

def rewrite_question(llm, user_input, filename):
    source = clean_source(filename)
    prompt = REWRITE_PROMPT.format(source=source, question=user_input)
    return llm.invoke(prompt).content.strip()

In [ ]:
# llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0, groq_api_key=os.getenv("GROQ_API_KEY"))

In [ ]:
# df['user_input'] = df.apply(lambda row: rewrite_question(llm, row['user_input'], row['filename']), axis=1)

In [ ]:
# df.to_json("evaluation/testset/new_testset_rewritten.jsonl", orient='records', lines=True)

In [ ]:
# vectorstore_db = vectorstore(documents=docs, batch_size=250)

# 2. Synthetic QA Dataset Generation

In [5]:
# imports for synthetic QA Dataset Generation
from ragas import RunConfig
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_ollama import ChatOllama                     # ollama can run locally
from langchain_huggingface import HuggingFaceEmbeddings

In [ ]:
# csv files are temporarily filtered out because they are large and dominate the dataset
# gen_docs = [file for file in docs if not file.metadata['filename'].endswith('.csv')]

# subsample documents to control cost and runtime during synthetic QA generation
# random_docs = random.sample(gen_docs, 200)

In [179]:
generator_llm = LangchainLLMWrapper(
                ChatOllama(
                    model="qwen2.5",
                    temperature=0,
                    # model_kwargs={"response_format":{"type":"json_object"}}
                    format="json"
                    )
                )

generator_embeddings = LangchainEmbeddingsWrapper(
                HuggingFaceEmbeddings(
                    model_name="BAAI/bge-large-en-v1.5",
                    model_kwargs={'device': 'cpu'},
                    encode_kwargs={'normalize_embeddings': True, 'batch_size': 32}
                    )
                )    

run_config = RunConfig(max_workers=2, timeout=180)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 4098.45it/s]

In [ ]:
def define_testset_size(chunks):
    if len(chunks) > 40:
        return 3
    elif len(chunks) > 20:
        return 2
    else:
        return 1

def save_checkpoints(data, file_path):

    if isinstance(data,dict):
        records = [data]
    elif isinstance(data, pd.DataFrame):
        records = data.to_dict(orient='records')
    elif hasattr(data, "to_pandas") and callable(data.to_pandas):
        records = data.to_pandas().to_dict(orient='records')
    else:
        raise ValueError("Unsupported data type for checkpoint saving")

    # Implementation for saving checkpoint
    with open(file_path, 'a') as f:
        for record in records:
            f.write(json.dumps(record) + '\n')

In [205]:
from src.eval import generate_qa_dataset

In [ ]:
def create_test_set(docs, file_path):
    for file, doc in docs.items():
        testset_size = define_testset_size(doc)
        testset = generate_qa_dataset(
                                doc, generator_llm, generator_embeddings,  
                                run_config=run_config,
                                testset_size=testset_size
                            )
        df = testset.to_pandas()
        df["filename"] = file
        save_checkpoints(df, file_path)

# 3. RAG Pipeline Execution

In [ ]:
df = pd.read_json("test_data/rag_evaluation_testset.json")

In [ ]:
vectorstore_db = vectorstore()

In [ ]:
df_32 = pd.read_json("test_data/curated_rag_evaluation_testset_32.jsonl", orient="records", lines=True)

In [ ]:
generate_rag_responses(df_32[31:], vectorstore_db, session_id="test_session", k=20)

# 4. RAG Evaluation

In [6]:
from ragas import RunConfig
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_huggingface import HuggingFaceEmbeddings
from ragas.metrics import (
    LLMContextPrecisionWithReference,
    LLMContextRecall,
    Faithfulness,
    ResponseRelevancy,
)
from langchain_google_genai import ChatGoogleGenerativeAI

In [7]:
evaluator_llm = LangchainLLMWrapper(
                    ChatGoogleGenerativeAI(
                        model="gemini-flash-lite-latest",
                        temperature=0,
                        # model_kwargs={"response_format": {"type": "json_object"}},
                    )
                )
evaluator_embeddings = LangchainEmbeddingsWrapper(
                        HuggingFaceEmbeddings(
                            model_name="BAAI/bge-large-en-v1.5",
                            model_kwargs={'device': 'cpu'},
                            encode_kwargs={'normalize_embeddings': True, 'batch_size': 32}
                            )
                        )

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 15593.99it/s]

In [8]:
metrics = [
    LLMContextPrecisionWithReference(llm=evaluator_llm),
    LLMContextRecall(llm=evaluator_llm),
    Faithfulness(llm=evaluator_llm),
    ResponseRelevancy(llm=evaluator_llm, embeddings=evaluator_embeddings),
]

run_config = RunConfig(max_workers=1, timeout=600)

In [16]:
file_path = "evaluation/rag_eval_v6.csv"

# with open("test_data/rag_results_v7.jsonl", "r") as f:
#     rag_results = [json.loads(line) for line in f]

In [93]:
df = get_results("evaluation/eval_results/rag_eval_baseline.jsonl")

In [ ]:
df['reference'][1]

'Microalgae, particularly Chlamydomonas reinhardtii, can be genetically engineered to enhance the production of antiviral double-stranded RNA (dsRNA) through a novel convergent promoter expression system. This genetic modification allows for the development of advanced genetic and molecular ways to employ microalgae as green bioreactors for producing biopharmaceuticals, which are classified as safe by the Food and Drug Administration (FDA). The enhanced production of antiviral dsRNA in Chlamydomonas reinhardtii could have potential applications in aquatic disease management, especially for diseases affecting shrimp and fish larvae.'

In [76]:
df['response'][1]

'**Genetic engineering strategy**\n\n1. **Design a convergent‑promoter cassette** –  \n   * A novel vector (p2XTRBL) carries two promoters that face each other in the chloroplast genome. When a target sequence is placed between them, each promoter drives transcription of opposite strands, producing complementary RNAs that anneal to form double‑stranded RNA (dsRNA).\n\n2. **Insert the antiviral target fragment** –  \n   * The 307‑bp fragment of the white‑spot‑syndrome‑virus (WSSV) VP28 gene is cloned into the convergent‑promoter cassette. In the study this fragment was first assembled in p2XTRBL and then sub‑cloned into the chloroplast transformation vector pSS116 using Golden‑Gate assembly.\n\n3. **Transform the chloroplast** –  \n   * The recombinant pSS116 plasmid is introduced into the chloroplast of *Chlamydomonas reinhardtii* (e.g., by the low‑cost biolistic or glass‑bead method). Because the cassette is marker‑less, selection of transgenic cells can be done by PCR or by screening for dsRNA production rather than antibiotic resistance.\n\n4. **Confirm expression** –  \n   * PCR verifies integration of the cassette, and transcript analysis (e.g., RT‑PCR, Northern blot) confirms that large amounts of VP28 dsRNA are produced in the algal cells.\n\n**Resulting phenotype** – The engineered algae accumulate high levels of VP28 dsRNA in their chloroplasts, which can be harvested directly or used alive as a feed ingredient.\n\n---\n\n**Potential applications in aquatic disease management**\n\n| Application | How the engineered algae are used | Expected benefit |\n|-------------|-----------------------------------|------------------|\n| **Oral vaccine for shrimp** (e.g., *Penaeus vannamei*) | Shrimp post‑larvae are fed live or dried *C. reinhardtii* cells that contain VP28 dsRNA. The dsRNA is taken up in the gut, triggers RNA‑i–mediated silencing of the viral VP28 gene, and protects the shrimp from WSSV infection. | Survival after WSSV challenge rose to **≈95\u202f%** (vs. control). |\n| **Broad‑spectrum antiviral platform** | The convergent‑promoter system can be re‑programmed with dsRNA sequences targeting other shrimp or fish viruses (e.g., other crustacean viral pathogens). | Provides a flexible, rapid response tool for emerging viral threats. |\n| **Sustainable, environmentally friendly disease control** | Algae are cultivated on a large scale with low inputs, require no antibiotics or chemicals, and can be incorporated directly into feed formulations. | Reduces reliance on chemotherapeutics, lowers environmental impact, and supports eco‑friendly aquaculture. |\n| **Potential extension to other aquaculture species** | Similar dsRNA‑expressing algae could be fed to crayfish, fish, or mollusks to protect against species‑specific viruses. | Expands the technology beyond shrimp to a wider range of aquaculture enterprises. |\n\nIn summary, by inserting a convergent‑promoter dsRNA cassette (e.g., VP28 dsRNA) into the chloroplast genome of *Chlamydomonas reinhardtii* using vectors such as p2XTRBL/pSS116 and Golden‑Gate assembly, researchers can generate algae that produce large amounts of antiviral dsRNA. When these algae are fed to cultured shrimp, they act as an oral RNA‑i vaccine, dramatically increasing survival after WSSV exposure and offering a scalable, eco‑friendly strategy for managing viral diseases in aquaculture.'

In [77]:
df['user_input'][1]

'How can microalgae, specifically Chlamydomonas reinhardtii, be genetically engineered to enhance the production of antiviral dsRNA and what are its potential applications in aquatic disease management?'

In [94]:
get_score(df)

llm_context_precision_with_reference    0.364444
context_recall                          0.494643
faithfulness                            0.728638
answer_relevancy                        0.703098
dtype: float64

In [90]:
get_score(df)

llm_context_precision_with_reference    0.355429
context_recall                          0.479708
faithfulness                            0.706338
answer_relevancy                        0.676252
dtype: float64

# Result Analysis

In [4]:
df_20 = pd.read_json("evaluation/eval_results/rag_eval_v4.jsonl", orient="records", lines=True)
length_20 = len(df_20)
print(length_20)

50

In [5]:
df_15 = pd.read_json("evaluation/eval_results/rag_eval_v3.jsonl", orient="records", lines=True)[:length_20]
df_10 = pd.read_json("evaluation/eval_results/rag_eval_v2.jsonl", orient="records", lines=True)[:length_20]
df_base = pd.read_json("evaluation/eval_results/rag_eval_baseline.jsonl", orient="records", lines=True)[:length_20]

In [6]:
print("k=20")
print("--"*30)
print(get_score(df_20))
print("k=15")
print("--"*30)
print(get_score(df_15))
print("--"*30)
print("k=10")
print("--"*30)
print(get_score(df_10))
print("--"*30)
print("k=4")
print("--"*30)
print(get_score(df_base))
print("--"*30)

k=20
------------------------------------------------------------
llm_context_precision_with_reference    0.348354
context_recall                          0.707143
faithfulness                            0.736247
answer_relevancy                        0.799792
dtype: float64
k=15
------------------------------------------------------------
llm_context_precision_with_reference    0.348248
context_recall                          0.642143
faithfulness                            0.685080
answer_relevancy                        0.818989
dtype: float64
------------------------------------------------------------
k=10
------------------------------------------------------------
llm_context_precision_with_reference    0.352081
context_recall                          0.628810
faithfulness                            0.715889
answer_relevancy                        0.787648
dtype: float64
------------------------------------------------------------
k=4
------------------------------------------------------------
llm_context_precision_with_reference    0.364444
context_recall                          0.494643
faithfulness                            0.728638
answer_relevancy                        0.703098
dtype: float64
------------------------------------------------------------

In [132]:
display_context_recall_failures(df_15, max_height=300)

Number of zero context recall cases: 2
Indices of unanswerable responses: [0, 4]

In [118]:
unanswerable_responses(df)

Number of unanswerable responses: 0

Empty DataFrame
Columns: [user_input, retrieved_contexts, response, reference, llm_context_precision_with_reference, context_recall, faithfulness, answer_relevancy]
Index: []

In [20]:
len([0, 4, 5, 8, 14, 18, 20, 28, 30, 32, 35, 36, 37, 38, 41, 42, 43, 46, 47])
len([0, 4, 8, 14, 20, 28, 32, 35, 36, 41, 43, 47])

12

In [140]:
[0, 4, 5, 8, 14, 18, 20, 28, 30, 32, 35, 36, 37, 38, 41, 42, 43, 46, 47]
index = 8

In [141]:
df.iloc[index][['llm_context_precision_with_reference','context_recall', 'faithfulness','answer_relevancy']]

llm_context_precision_with_reference         0.0
context_recall                               0.0
faithfulness                            0.909091
answer_relevancy                        0.923053
Name: 8, dtype: object

In [142]:
from pprint import pformat
import ast
print("-"*30, "User Input","-"*30)
print(pformat(df.iloc[index]['user_input']))
print('\n',"-"*30,"Response","-"*30)
print(pformat(df.iloc[index]['response']))
print('\n',"-"*30,"Reference","-"*30)
print(pformat(df.iloc[index]['reference']))
print('\n',"-"*30,"Retrieved Contexts","-"*30)
print(pformat(df.iloc[index]['retrieved_contexts']))

------------------------------ User Input ------------------------------
'What is the 2026 Annualized Estimated Tax Worksheet used for?'

 ------------------------------ Response ------------------------------
('The 2026\u202fAnnualized Estimated Tax Worksheet (Worksheet\u202f2‑9) is the '
 'tool you use to **figure your estimated tax payments when you apply the '
 'annualized‑income‑installment method**.  \n'
 '\n'
 'It lets you:\n'
 '\n'
 '* Annualize your income, deductions and credits at the end of each payment '
 'period and compute the tax that should be paid for that period.  \n'
 '* Estimate tax when the period includes special items such as net capital '
 'gains, qualified dividends, or a foreign‑earned‑income or housing '
 'exclusion/deduction (via Worksheets\u202f2‑10 and\u202f2‑11).  \n'
 '* Re‑figure or amend your estimated‑tax calculations during the year '
 '(Worksheet\u202f2‑12).  \n'
 '\n'
 'The amount you calculate on the worksheet (line\u202f32) is then used to '
 'determine the required quarterly estimated‑tax payments and to complete the '
 'payment vouchers.')

 ------------------------------ Reference ------------------------------
('Worksheet 2-10 is used to keep records and calculate tax based on specific '
 'lines of income and expenses as per the 2026 Tax Rate Schedules. It involves '
 'multiplying line 35 by 28%, adding certain lines, and determining the '
 'smaller tax amount from two calculations for entry.')

 ------------------------------ Retrieved Contexts ------------------------------
['2026 Annualized Estimated Tax Worksheet—Line 12\n'
 'Foreign Earned Income Tax Worksheet\n'
 '\n'
 'Worksheet 2-11.\n'
 'Keep for Your Records\n'
 '\n'
 'Before you begin: If line 11 of Worksheet 2-9 (2026 Annualized Estimated Tax '
 'Worksheet) is zero for the period, don’t complete this\n'
 'worksheet.\n'
 '\n'
 '1. Enter the amount from line 11 of your 2026 Annualized Estimated Tax '
 'Worksheet for the period 1.\n'
 '2. Enter the annualized amount* of foreign earned income and housing amount '
 'you (and your spouse if\n'
 '\n'
 'filing jointly) expect to exclude or deduct for the period on Form 2555 2.\n'
 '3. Add lines 1 and 2 3.\n'
 '4. Tax on the amount on line 3. Use the 2026 Tax Rate Schedules or Worksheet '
 '2-10,** as\n'
 '\n'
 'appropriate 4.\n'
 '5. Tax on the amount on line 2. Use the 2026 Tax Rate Schedules 5.\n'
 '6. Subtract line 5 from line 4. Enter the result here and on line 12 of your '
 '2026 Annualized Estimated Tax\n'
 '\n'
 'Worksheet (Worksheet 2-9). If zero or less, enter -0- 6.',
 'to estimate your income tax if line 1 of your Annualized ES Worksheet '
 'includes a net capital gain or\n'
 'qualified dividends—line 12 of Annualized ES Worksheet Worksheet 2-10\n'
 '\n'
 'to estimate your income tax if you expect to claim a foreign earned income '
 'exclusion or foreign housing\n'
 'exclusion or deduction on Form 2555—line 12 of Annualized ES Worksheet '
 'Worksheet 2-11\n'
 '\n'
 'to refigure (amend) your estimated tax during the year Worksheet 2-12\n'
 '\n'
 'Page 30 of 48 Fileid: … cation-505/2026/a/xml/cycle03/source 10:57 - '
 '31-Mar-2026\n'
 'The type and rule above prints on all proofs including departmental '
 'reproduction proofs. MUST be removed before printing.\n'
 '\n'
 '30 Chapter 2 Estimated Tax for 2026 Publication 505 (2026)\n'
 '\n'
 '2026 Tax Rate Schedules\n'
 '\n'
 'CAUTION\n'
 '!\n'
 '\n'
 'Don’t use these Tax Rate Schedules to figure your 2025 taxes. Use them only '
 'to figure your 2026 estimated\n'
 'taxes.\n'
 'Schedule X—Use if your 2026 filing status is\n'
 'Single\n'
 '\n'
 'Schedule Z— Use if your 2026 filing status is\n'
 'Head of household',
 'Divide line 19 by the annualization amount shown on Worksheet 2-9, line 2, '
 'for the same\n'
 'period and enter here. Include this amount in the total on line 1 of your '
 '2026 Estimated\n'
 'Tax Worksheet (Worksheet 2-1) (or Annualized Estimated Tax Worksheet '
 '(Worksheet\n'
 '2-9)) 20.\n'
 '\n'
 'Page 33 of 48 Fileid: … cation-505/2026/a/xml/cycle03/source 10:57 - '
 '31-Mar-2026\n'
 'The type and rule above prints on all proofs including departmental '
 'reproduction proofs. MUST be removed before printing.\n'
 '\n'
 'Publication 505 (2026) Chapter 2 Estimated Tax for 2026 33\n'
 '\n'
 '2026 Estimated Tax Worksheet—Lines 1 and 9\n'
 'Estimated Self-Employment Tax and Deduction Worksheet\n'
 '\n'
 'Worksheet 2-3.\n'
 'Keep for Your Records\n'
 '\n'
 '1 a. Enter your expected income and profits subject to self-employment\n'
 'tax* 1a. .\n'
 '\n'
 'b. If you will have farm income and also receive social security retirement '
 'or\n'
 'disability benefits, enter your expected Conservation Reserve Program\n'
 'payments that will be included on Schedule F (Form 1040) or listed on\n'
 'Schedule K-1 (Form 1065) 1b.',
 'Page 29 of 48 Fileid: … cation-505/2026/a/xml/cycle03/source 10:57 - '
 '31-Mar-2026\n'
 'The type and rule above prints on all proofs including departmental '
 'reproduction proofs. MUST be removed before printing.\n'
 '\n'
 'Publication 505 (2026) Chapter 2 Estimated Tax for 2026 29\n'
 '\n'
 'https://fed.acipayonline.com\n'
 'https://www.PAY1040.com\n'
 'https://www.eftps.gov\n'
 'https://www.irs.gov/payments/pay-with-cash-at-a-retail-partner\n'
 '\n'
 'Worksheets for Chapter 2\n'
 'Use the following worksheets and tables to figure your correct estimated '
 'tax.\n'
 '\n'
 'IF you need THEN use\n'
 '2026 Tax Rate Schedules 2026 Tax Rate Schedules\n'
 '\n'
 'the 2026 Estimated Tax Worksheet Worksheet 2-1\n'
 '\n'
 'to estimate your taxable social security and railroad retirement '
 'benefits—line 1 of ES Worksheet (or\n'
 'Annualized ES Worksheet (Worksheet 2-9)) Worksheet 2-2\n'
 '\n'
 'to estimate your self-employment (SE) tax and your deduction for SE '
 'tax—lines 1 and 11 of ES Worksheet\n'
 '(lines 1 and 17 of Annualized ES Worksheet (Worksheet 2-9)) Worksheet 2-3',
 'Worksheet 2-8.\n'
 'Keep for Your Records\n'
 '\n'
 'Before you begin: If line 3 of your 2026 Estimated Tax Worksheet (Worksheet '
 '2-1) is zero, don’t complete this worksheet.\n'
 '1. Enter the amount from line 3 of your 2026 Estimated Tax Worksheet '
 '(Worksheet 2-1) 1.\n'
 '2. Enter the total foreign earned income and housing amount you (and your '
 'spouse if filing jointly) expect to\n'
 '\n'
 'exclude or deduct in 2026 on Form 2555 2.\n'
 '3. Add lines 1 and 2 3.\n'
 '4. Tax on the amount on line 3. Use the 2026 Tax Rate Schedules or Worksheet '
 '2-7,* as appropriate 4.\n'
 '5. Tax on the amount on line 2. Use the 2026 Tax Rate Schedules 5.\n'
 '6. Subtract line 5 from line 4. Enter the result here and on line 4 of your '
 '2026 Estimated Tax Worksheet\n'
 '\n'
 '(Worksheet 2-1). If zero or less, enter -0- 6.',
 'Worksheet 1-2.\n'
 '\n'
 'Page 14 of 48 Fileid: … cation-505/2026/a/xml/cycle03/source 10:57 - '
 '31-Mar-2026\n'
 'The type and rule above prints on all proofs including departmental '
 'reproduction proofs. MUST be removed before printing.\n'
 '\n'
 '14 Chapter 1 Tax Withholding for 2026 Publication 505 (2026)\n'
 '\n'
 'Worksheet 1-3. Projected Tax for 2026 Keep for Your Records\n'
 '.\n'
 '\n'
 'Use this worksheet to figure your projected tax for 2026. Note: Enter '
 'combined amounts if Married filing jointly.\n'
 '1. Enter amount of adjusted gross income (AGI) you expect in 2026. (To '
 'determine this, you may want to start with\n'
 '\n'
 'the AGI on your last year’s return, and add or subtract your expected '
 'changes. Also, take into account items listed\n'
 'under What’s New for 2026 and the Reminders section, earlier.)\n'
 'Note: If self-employed, first complete Worksheet 2-3 to figure your expected '
 'deduction for self-employment tax.\n'
 'Subtract the amount from Worksheet 2-3, line 11, to figure the line 1 entry '
 '1.',
 'You must make adjustments both for\n'
 'changes in your own situation and for recent\n'
 'changes in the tax law. Some of these changes\n'
 'are discussed earlier under What’s New for\n'
 '2026 and the Reminders section. For information about these and other '
 'changes in the law,\n'
 'visit the IRS website at IRS.gov.\n'
 '\n'
 'The instructions for Form 1040-ES include a\n'
 'worksheet to help you figure your estimated tax.\n'
 'Keep the worksheet for your records.\n'
 '\n'
 '2026 Estimated Tax\n'
 'Worksheet\n'
 '\n'
 'If you file Form 1040-SS use the Estimated Tax Worksheet for Filers of Form\n'
 '1040-SS, in Form 1040-ES to figure\n'
 '\n'
 'your estimated tax.\n'
 '\n'
 'Use Worksheet 2-1 to help guide you\n'
 'through the information about completing the\n'
 '2026 Estimated Tax Worksheet. You can also\n'
 'find a copy of the worksheet in the instructions\n'
 'for Form 1040-ES.\n'
 '\n'
 'Expected AGI—Line 1\n'
 'Your expected AGI for 2026 (line 1) is your expected total income minus your '
 'expected adjustments to income.',
 'The annualized income installment method\n'
 'annualizes your tax at the end of each period\n'
 'based on a reasonable estimate of your income, deductions, and other items '
 'relating to\n'
 'events that occurred from the beginning of the\n'
 'tax year through the end of the period. To see\n'
 'whether you can pay less for any period, complete the 2026 Annualized '
 'Estimated Tax Worksheet (Worksheet 2-9).\n'
 '\n'
 'You first must complete the 2026 Estimated Tax Worksheet (Worksheet 2-1)\n'
 'through line 14b.\n'
 '\n'
 'Use the result you figure on line 32 of Worksheet 2-9 to make your estimated '
 'tax payments\n'
 'and complete your payment vouchers.\n'
 '\n'
 'Note: If you use the annualized income installment method to figure your '
 'estimated tax\n'
 'payments, you must file Form 2210 with your\n'
 '2026 tax return. See Schedule AI—Annualized\n'
 'Income Installment Method in the Instructions\n'
 'for Form 2210 for more information.\n'
 '\n'
 'Instructions for the 2026\n'
 'Annualized Estimated Tax\n'
 'Worksheet (Worksheet 2-9)\n'
 '\n'
 'Use Worksheet 2-9 to help you follow\n'
 'these instructions.',
 'CAUTION\n'
 '!\n'
 '\n'
 'When this worksheet refers you to instructions, you can find those '
 'instructions in the 2026 Form 1040-ES.\n'
 '\n'
 '1. Adjusted gross income you expect in 2026 (see instructions) 1.\n'
 '2a. Deductions • If you plan to itemize deductions, enter the estimated '
 'total of your itemized deductions\n'
 'Caution: If you plan to itemize your deductions and claim a charitable '
 'contribution deduction, see Worksheet 2-5 to\n'
 'figure the amount of your deduction.\n'
 'Caution: If your expected taxable income will be more than $768,700 if '
 'married filing jointly or qualifying widower;\n'
 '$640,600 if head of household or single; $384,350 if married filing '
 'separately, your itemized deductions may be\n'
 'reduced. See Worksheet 2-6 to figure the amount of your deduction.• If you '
 'don’t plan to itemize deductions, enter your standard deduction plus up to '
 '$1,000 ($2,000 for married',
 'Publication 505 (2026) Chapter 2 Estimated Tax for 2026 25\n'
 '\n'
 'Amended Estimated Tax WorksheetWorksheet 2-12.\n'
 'Keep for Your Records\n'
 '\n'
 '1. Amended total estimated tax due 1.\n'
 '2. Multiply line 1 by:\n'
 '\n'
 '50% (0.50) if next payment is due June 15, 2026\n'
 '75% (0.75) if next payment is due September 15, 2026\n'
 '100% (1.00) if next payment is due January 15, 2027 2.\n'
 '\n'
 '3. Estimated tax payments for all previous periods 3.\n'
 '4. Next required payment: Subtract line 3 from line 2 and enter the result '
 '(but not\n'
 '\n'
 'less than zero) here and on your payment voucher for your next required\n'
 'payment 4.\n'
 'Note: If the payment on line 4 is due January 15, 2027, stop here. '
 'Otherwise,\n'
 'go to line 5.\n'
 '\n'
 '5. Add lines 3 and 4 5.\n'
 '6. Subtract line 5 from line 1 and enter the result (but not less than zero) '
 '6.\n'
 '7. Each following required payment: If the payment on line 4 is due June 15, '
 '2026, enter one-half of the']

In [100]:
word = "Annualized Estimated "
context_list = df.iloc[index]["retrieved_contexts"]

In [58]:
[i for i, ctx in enumerate(context_list)if word in ctx]

NameError: name 'context_list' is not defined

In [96]:
context_list[2]

'Divide line 19 by the annualization amount shown on Worksheet 2-9, line 2, for the same\nperiod and enter here. Include this amount in the total on line 1 of your 2026 Estimated\nTax Worksheet (Worksheet 2-1) (or Annualized Estimated Tax Worksheet (Worksheet\n2-9)) 20.\n\nPage 33 of 48 Fileid: … cation-505/2026/a/xml/cycle03/source 10:57 - 31-Mar-2026\nThe type and rule above prints on all proofs including departmental reproduction proofs. MUST be removed before printing.\n\nPublication 505 (2026) Chapter 2 Estimated Tax for 2026 33\n\n2026 Estimated Tax Worksheet—Lines 1 and 9\nEstimated Self-Employment Tax and Deduction Worksheet\n\nWorksheet 2-3.\nKeep for Your Records\n\n1 a. Enter your expected income and profits subject to self-employment\ntax* 1a. .\n\nb. If you will have farm income and also receive social security retirement or\ndisability benefits, enter your expected Conservation Reserve Program\npayments that will be included on Schedule F (Form 1040) or listed on\nSchedule K-1 (Form 1065) 1b.'

In [21]:
import time